### ISSUE TITLE
next up:  javascript in the context of a real (but not yet shiny) webapp

### ISSUE THREAD

**Issue by paul-shannon** [mariam16548/learningShiny#2]
Hi @mariam16548,

You had earlier found, and were enthusiastic about, a web-based course on (I think) web programming.  Perhaps from coursera? 

Something like that now seems like just the right thing.  Another candidate might be these Harvard youtube lectures:  https://www.youtube.com/playlist?list=PLhQjrBD2T382hIW-IsOVuXP1uMzEvmcE5

My *goal* is for you to have some direct experience with the HTTP protocol, especially the GET command.  It can be hard to grasp the dynamic client/server (browser/webapp) relationship.   It is pretty well hidden in shiny.  But you will enjoy and benefit from knowing about it.  And there is no better way than writing your own.

It may seem counter-intuitive, but the easiest way to learn client/server web programming uses python and javascript.   "flask" is the python module which most people use.   The Harvard CS50 lectures use python and flask.

My request:  watch the first three CS50 lectures to learn your way around.   Don't focus on complete understanding - that will come later.  Just watch and absorb.   The first lecture is about git - which you already know!  The second will also contain some familiar material after your good work this week.   Python & flask proper come in the third lecture.

The plan:  build a simple flask app, really simple, to get a solid grasp of what happens in the web server (python + flask) and what happens in the web browser (the client, javascript, HTML and css).   

Then - promise! - it's on to shiny.

**Comment by mariam16548** [comment]
Hi @paul-shannon 
This sounds like a great plan! I appreciate how you are allowing me to establish a strong foundation. I will get to work on this!

**Comment by mariam16548** [comment]
@paul-shannon 
My directory is called simpleFlaskApp. Feel free to give me any feedback!

**Comment by paul-shannon** [comment]
@mariam16548 
Be kind to the reader!   Leave a makefile, or at least notes, so that it is obvious how run your app.

**Comment by mariam16548** [comment]
Hi @paul-shannon, 
I tried leaving a makefile, but I'm not sure if I did it correctly. Let me know what you think!

**Comment by paul-shannon** [comment]
It appears :} that you did not actually run the makefile.

Here’s what I see:

  simpleFlaskApp> make
   make: Nothing to be done for `all’.


Please make this easy for me.

**Comment by mariam16548** [comment]
@paul-shannon 
Would you be able to check again to see if it works now?

**Comment by paul-shannon** [comment]
Nope.  Same as before.

Does it work for you?

If so, paste your commands into an email, show me!

 - Paul

**Comment by mariam16548** [comment]
@paul-shannon 

I think I figured out where I went wrong. As for my commands, I just typed `make` into the terminal (while making sure I was in the right directory as well). If you try one more time, I think it should work?

**Comment by paul-shannon** [comment]
Mariam,

I asked this in my last message. 

    If so, paste your commands into an email, show me!

By “show me” I mean show me that (and how) running your makefile works. Paste in your prompt, the command you  type, and the output that is generated.

If this is all confusing, please give me a call.

 - Paul

**Comment by mariam16548** [comment]
@paul-shannon 
Okay, I'll give you a call!

**Comment by mariam16548** [comment]
@paul-shannon 
FLASK_APP=simpleHelloApp.py FLASK_ENV=development FLASK_DEBUG=1 flask run

 * Serving Flask app "simpleHelloApp.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 242-137-366

**Comment by mariam16548** [comment]
Mariams-Air:simpleFlaskApp mariamb$ make
FLASK_APP=simpleHelloApp.py FLASK_ENV=development FLASK_DEBUG=1 flask run

 * Serving Flask app "simpleHelloApp.py" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 242-137-366
127.0.0.1 - - [17/Jul/2020 18:41:19] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Jul/2020 18:41:23] "POST /hello HTTP/1.1" 200 -
