### ISSUE TITLE
Flask App updated!

### ISSUE THREAD

**Issue by mariam16548** [mariam16548/learningShiny#3]
Hi @paul-shannon, 
I updated the flask app (changed it so that I can reenter names and change the display), please let me know if you have any feedback! I will continue to work on the Shiny app!

**Comment by paul-shannon** [comment]
Hi @mariam16548,

Nice trick!  (assigning me, that is).  clever.  and effective:  I just pulled your changes, see that your code now does what we were aiming at.

**Comment by mariam16548** [comment]
@paul-shannon 
Great! 
Here is the progress report for today:

- I updated the Flask app (a small problem I ran into was whenever I opened the app, "Hello None!" pops up-- I ended up fixing this!). 

- I learned more about:  
 **curl -v -s -k -L https://igv-data.systemsbiology.net/static/hintDemo/footprints.bed  2>&1 | grep Content** 

**curl** 
  - Retrieves data from this url, and the returned data is then passed to the next command, **grep**, to search through the reply. 

The **-** switches and the **>** redirection will modify the behavior of the command. Specifically for the switches: 
**-v** 
  - This allows for **curl** to be verbose during the operation, which is useful for debugging. 

**-s** 
  - This is for silent mode (don't show progress meter or error messages).

**-k** 
  - This is for insecure-- allowing for **curl** to proceed and operate even for server connections otherwise considered insecure. 

**-L** 
  - This is for location, if the server reports that the requested page has moved to a different location, this option will make **curl** redo the request in the new place. 

So far, I've been reviewing Shiny tutorials and continuing to work on the Shiny app. I should have it up on GitHub by tomorrow.

**Comment by paul-shannon** [comment]
Hi Mariam,

Could you rewrite your message using paragraphs?   White space to separate the different topics you cover? 

Isolate commands so that they stand alone in the middle of white space?

 - Paul

**Comment by mariam16548** [comment]
Hi @paul-shannon, 
Here is my rewritten message (I tried making it more readable by separating the different ideas with white space and bullet points for more of a paragraph-style indentation-- I'm unsure if you would like for me to add more detail instead). If I misunderstood, please let me know!

Here is the progress report for today:

- I updated the Flask app (a small problem I ran into was whenever I opened the app, "Hello None!" pops up-- I ended up fixing this!). 

- I learned more about:  
 **curl -v -s -k -L https://igv-data.systemsbiology.net/static/hintDemo/footprints.bed  2>&1 | grep Content** 

**curl** 
  - Retrieves data from this url, and the returned data is then passed to the next command, **grep**, to search through the reply. 

The **-** switches and the **>** redirection will modify the behavior of the command. Specifically for the switches: 
**-v** 
  - This allows for **curl** to be verbose during the operation, which is useful for debugging. 

**-s** 
  - This is for silent mode (don't show progress meter or error messages).

**-k** 
  - This is for insecure-- allowing for **curl** to proceed and operate even for server connections otherwise considered insecure. 

**-L** 
  - This is for location, if the server reports that the requested page has moved to a different location, this option will make **curl** redo the request in the new place. 

So far, I've been reviewing Shiny tutorials and continuing to work on the Shiny app. I should have it up on GitHub by tomorrow.

**Comment by mariam16548** [comment]
Hi @paul-shannon, 
I just add the Shiny app into a directory called: "shiny_example". Please let me know what you think!

**Comment by paul-shannon** [comment]
@mariam16548:
Relative to the existing naming practices in this repo:

 -  do you see any redundancy in your directory name, "shiny_example"?
 - do you see consistency, or inconsistency, in the use of case and underscores?
 - will the reader know what the directory contains?

**Comment by mariam16548** [comment]
Hi @paul-shannon 
- Now that I am looking back, I do see the redundancy in the directory name. 
- I also took out the underscore to stick to only using upper/lowercase.
- I renamed the directory to make it more clear/give more information. 

Thank you for your suggestions!

**Comment by paul-shannon** [comment]
bravo!

**Comment by mariam16548** [comment]
@paul-shannon 
Progress report for today:
- I worked on the Shiny app, referenced some Shiny tutorials. I put it up on GitHub. I updated the name of the directory to give it a more appropriate name.
- I looked into the RStudio question that you posted-- I spent some time looking up terms and making sure I understood the background information.

**Comment by paul-shannon** [comment]
@mariam16548 - good work on the shiny app.  It works!

AND it is not yet very handsome.  So now is good time to learn css, and apply it here.  

Make it beautiful!

**Comment by mariam16548** [comment]
@paul-shannon Okay, I'll get to work on it!

**Comment by mariam16548** [comment]
Hi @paul-shannon, 
I just updated the shiny app, please let me know what you think!

**Comment by mariam16548** [comment]
Progress report for today: 
- I spent most of my time trying different ways of integrating CSS into my Shiny app. There were a few bugs I ran into, but I was able to figure them out!. I also read through a lot of material to have more background knowledge. 

I hope you have a wonderful weekend!

**Comment by paul-shannon** [comment]
green!  nice use of color and font.   
The submit button is way off in right field in my browser.  
Can you build the document (the page) so that all elements are grouped together?  All all in the center of the page?  And everything remains centered & grouped as you manually resize the browser window?

**Comment by mariam16548** [comment]
@paul-shannon 
I'll get to work on this!

**Comment by mariam16548** [comment]
@paul-shannon 
Here is today's progress report: 
- I spent some time reviewing the htmlwidgetsMinimal repo and trying to understand the code behind it. 
- I'm still working centering the elements on the page-- I should be done by tomorrow.

**Comment by paul-shannon** [comment]
@mariam16548 good!   I'd say push deep on both of those things, push until you have them strong and sure.
It appears that htmlwidgets (without shiny) does not provide back-and-forth messaging, R <-> browser.   I sure hope I am wrong.

**Comment by mariam16548** [comment]
Hi @paul-shannon, 
Here is today's progress report:
- I just updated the shiny app to center the elements on the page-- I ran into a couple of bugs along the way, but I was able to figure it out!
- I took some time to learn more about Bootstrap, which Shiny leverages, to understand more CSS 
- I also continued to delve more into learning the code behind htmlwidgetsMinimal

**Comment by paul-shannon** [comment]
@mariam16548   Good work!
could you close this issue, start a new one with fitting title?   I am a sticker, enthusiast and rabid true believer in good naming practices.
