### ISSUE TITLE
simpleHelloApp Updated!

### ISSUE THREAD

**Issue by mariam16548** [mariam16548/learningShiny#4]
@paul-shannon 
Here is the new issue!

Today's progress report:
- I just updated the shiny app to center the elements on the page-- I ran into a couple of bugs along the way, but I was able to figure it out!
- I took some time to learn more about Bootstrap, which Shiny leverages, to understand more CSS
- I also continued to delve more into learning the code behind htmlwidgetsMinimal

**Comment by mariam16548** [comment]
Hi @paul-shannon, 
Today's progress report:
- I looked through the code behind igvShiny and cyjShiny. 
- I tried to understand what each part of the code does to serve its general purpose. 

Also, I mentioned a while ago that as a part of my Bioengineering major, they would like for mentors to fill out a short evaluation form on our progress so that we can have some feedback on our professional development. I will be sending you that form-- and if you would be able to send it back to me by next Friday (8/7), I would appreciate it!

**Comment by mariam16548** [comment]
Hi @paul-shannon,
Here is today's progress report:
- I looked through the code behind nglShiny.
- I tried to understand what each part of the code does to serve its general purpose.

**Comment by paul-shannon** [comment]
Hi Mariam,

“tried to understand…”   any questions or puzzles I can help with?

**Comment by mariam16548** [comment]
Hi @paul-shannon, 
I'm still learning by looking up functions I'm unfamiliar with, etc. but I'll let you know if I have other specific questions!

**Comment by paul-shannon** [comment]
Here’s a challenge for you!   Write a custom (if slightly silly) hello world widget, an htmlwidget of your own,  which does what your flask and shiny app did:

   in javascript:  presents a text input html element, a button, and a results div
   accompanied in the R code, all that is needed to invoke and display and operate

This will present you with harder questions, push the limits of your understanding.  Since you are an engineer, however, you need to BUILD as well as read.

 - Paul

**Comment by mariam16548** [comment]
@paul-shannon 
I'll get to work on that!

**Comment by mariam16548** [comment]
Hi @paul-shannon, 
It was great talking to you today!
Today's progress report: 
- I worked on the original htmlwidgets project and then after our phone call: 
- I've been looking up some of the terms that you mentioned (like Drake's equation, etc) to get more context on the new project-- I hope to continue looking into this on Monday. 
I'm really excited to start on this new project! Have a great weekend!
